#!/bin/bash

main_menu=$(echo "k8s cache" | tr " " "\n")

contexts=$(echo "dev/hmg prd" | tr " " "\n")
namespaces=$(echo "n1 n2 n3 n4 n5 n6" | tr " " "\n")
actions=$(echo "port-forward logs describe-pod" | tr " " "\n")

here=$(pwd)

main() {
    menu_seleceted_opt=$(echo "$main_menu" | fzf --header="select an option" --header-first)

    handle_db_flow
    handle_k8s_flow
}



handle_db_flow() {
    if [ "$menu_seleceted_opt" == "cache" ]; then
        db_opts=$(echo "reset" | tr " " "\n")
        db_seleceted_opt=$(echo "$db_opts" | fzf --header="select an option" --header-first)

        if [ "$db_seleceted_opt" == "reset" ]; then
            $here/database reset
        fi
    fi
}


handle_k8s_flow(){
    if [ "$menu_seleceted_opt" == "k8s" ]; then
        selected_ctx=$(echo "$contexts" | fzf --header="select a context" --header-first)
        selected_ns=$(echo "$namespaces" | fzf --header="select a namespace" --header-first)
        selected_action=$(echo "$actions" | fzf --header="select an action" --header-first)
    fi
}




# echo "$selected_ctx $selected_ns $selected_action"

main
